# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8247d91992d2e11a1ec88116bc2c0b3f1ea8970e6947541bd0dcca8375384742378bca4cc44582b3932a94724f886e22c65ac44770804ae032a32b08c55ab6a5

test:
  secret_key_base: 96367296658903fea80353f89fa3cca024a7604b77edb59753e4b9bb2ffe95e546165ae1b7306f403697dcbb4d7eed548838a02baa8278c1223c87b85a4350a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
